language: java
jdk:
  - oraclejdk8
  - openjdk11
sudo: required
before_install:
  - sudo apt-get -qq update || echo no sudo apt-get
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start || echo No X11
  - sleep 3
script:
  - mvn install -DskipTests
  - mvn -f $TEST_SUITE verify
os:
  - linux
  - osx
env:
  - TEST_SUITE=.
